"Remap leader
let mapleader=" "

"Search
"Search as you type
"Highlight results
"Smart case
"Use qq to remove the highlight
set incsearch
set hlsearch
set ignorecase
set smartcase
nnoremap <silent> & :nohl<CR>

"Remap escape
inoremap jj <Esc>

"Word for CamelCase words
nnoremap <leader>w /\u<CR>:nohlsearch<CR>

"Remap page moves
"Avoid scrolling one line by one line
noremap <C-J> }
noremap <C-K> {

"Remap save and quit
nnoremap qq :x<CR>

"Show matching chars
"Like () or {}
set showmatch

"Sort lines by lengh
function! SortLines() range
    execute a:firstline . "," . a:lastline . 's/^\(.*\)$/\=strdisplaywidth( submatch(0) ) . " " . submatch(0)/'
    execute a:firstline . "," . a:lastline . 'sort! n'
    execute a:firstline . "," . a:lastline . 's/^\d\+\s//'
endfunction

command -range -nargs=0 Lsort :<line1>,<line2>call SortLines()

