set termguicolors
set shortmess+=WI

"Remap leader
let mapleader=" "

"Split on right and on below
set splitright
set splitbelow
nnoremap <silent> <Leader>b :split<CR>
nnoremap <silent> <Leader>r :vsplit<CR>

"Buffers integration
set hidden
set history=500
nnoremap <silent> <C-H> :bprev<CR>
nnoremap <silent> <C-L> :bnext<CR>

"Search
"Search as you type
"Highlight results
"Smart case
"Use qq to remove the highlight
set ignorecase
set smartcase
set incsearch
set hlsearch
nnoremap <silent> & :nohl<CR>

"Identation
filetype plugin indent on
syntax enable
set nosmartindent
set cindent
set shiftwidth=4
set softtabstop=4
set expandtab
set list
"set listchars=tab:>-,trail:\u00b7
let &listchars="tab:\u2192 ,extends:>,precedes:<,trail:~"

"Word for CamelCase words
nnoremap <leader>w /\u<CR>:nohlsearch<CR>

"Remap page moves
"Avoid scrolling one line by one line
noremap <C-J> }
noremap <C-K> {

"Remap save and quit
nnoremap Q :x<CR>

"Show matching chars
set showmatch

"Sort lines by lengh
function! SortLines() range
    execute a:firstline . "," . a:lastline . 's/^\(.*\)$/\=strdisplaywidth( submatch(0) ) . " " . submatch(0)/'
    execute a:firstline . "," . a:lastline . 'sort! n'
    execute a:firstline . "," . a:lastline . 's/^\d\+\s//'
endfunction

command -range -nargs=0 Lsort :<line1>,<line2>call SortLines()
