#! /bin/sh

sxhkd &

bspc monitor DVI-0  --rename left  --reset-desktops 3 4
bspc monitor HDMI-0 --rename right --reset-desktops 1 2

bspc config border_width 4
bspc config window_gap   8

bspc config normal_border_color  "#A89984"
bspc config focused_border_color "#FE8019"

bspc config single_monocle     true
bspc config borderless_monocle true
bspc config gapless_monocle    false
