code --install-extension bmalehorn.vscode-fish
code --install-extension dbaeumer.vscode-eslint
code --install-extension EditorConfig.EditorConfig
code --install-extension ilyakooo0.ormolu
code --install-extension JakeBecker.elixir-ls
code --install-extension jcanero.hoogle-vscode
code --install-extension jdinhlife.gruvbox
code --install-extension justusadam.language-haskell
code --install-extension KevinRose.vsc-python-indent
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension mechatroner.rainbow-csv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension necinc.elmmet
code --install-extension PKief.material-icon-theme
code --install-extension Prisma.prisma
code --install-extension redhat.java
code --install-extension sbrink.elm
code --install-extension Vans.haskero
code --install-extension vigoo.stylish-haskell
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
