# CHMOD
alias cx='chmod +x'

# CP
alias cp='cp -v'
alias ccp='cp -R'

# DOCKER
alias d='docker'

# DU
alias du='du -h'
alias ddu='du -sh'

# GIT
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gca='git commit --all'
alias gck='git checkout'
alias gd='git diff'
alias gdt='git difftool'
alias gp='git push'
alias gst='git status'
alias gt='git log --oneline --decorate --all --graph'
alias gu='git pull'

# GREP
alias grep='grep --color'
alias egrep='egrep --color'

# LS
alias l='ls -l --color=auto'
alias la='ls -la --color=auto'

# MKDIR
alias mmkdir='mkdir -p'

# PYTHON
alias py='python3'

# RM
alias rrm='rm -Rf'

# VIM
alias e='vim'
alias v='view'

